---
- name: this is to demonstrate the template demo
  hosts: "*"
  vars: 
   env: Staging
   application_version: V9.5.36
  tasks:
   - name: Copying a config file from jinja2 template
     template: 
      src: "{{ item }}.j2"
      dest: /etc/{{ item }}
      owner: root
      group: root
      mode: 0600
     become: true
     loop:
      - my_app.conf
      - my_app.release 
